apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
    spec:
      containers:
          image: postgres:latest
          environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
          name: postgres
          ports:
          - containerPort: 5432
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: postgres-pv-clai
          